export const FETCH_SERIES_BEGIN = 'FETCH_SERIES_BEGIN'
export const FETCH_SERIES_SUCCESS = 'FETCH_SERIES_SUCCESS'
export const FETCH_SERIES_FAILURE = 'FETCH_SERIES_FAILURE'

export const UPDATE_SERIES = 'UPDATE_SERIES'
export const UPDATE_SERIES_METADATA = 'UPDATE_SERIES_METADATA'

export const RESET_DATA = 'RESET_DATA'