export const FETCH_SYMBOLS_BEGIN = 'FETCH_SYMBOLS_BEGIN'
export const FETCH_SYMBOLS_SUCCESS = 'FETCH_SYMBOLS_SUCCESS'
export const FETCH_SYMBOLS_FAILURE = 'FETCH_SYMBOLS_FAILURE'

export const LIST_SYMBOLS = 'LIST_SYMBOLS'